/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./src/components/ExceptionHandling/403.vue')['default']
    404: typeof import('./src/components/ExceptionHandling/404.vue')['default']
    500: typeof import('./src/components/ExceptionHandling/500.vue')['default']
    Account: typeof import('./src/components/CustomHeaderActive/account.vue')['default']
    Active: typeof import('./src/components/CustomHeaderActive/active.vue')['default']
    AdvancedTable: typeof import('./src/components/AdvancedTable/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    CountTo: typeof import('./src/components/Custom/count-to.vue')['default']
    CustomHeaderActive: typeof import('./src/components/CustomHeaderActive/index.vue')['default']
    CustomLayout: typeof import('./src/components/Layout/customLayout.vue')['default']
    CustomTabs: typeof import('./src/components/CustomTabs/index.vue')['default']
    EchartsContainer: typeof import('./src/components/EchartsContainer/index.vue')['default']
    ExceptionBase: typeof import('./src/components/ExceptionHandling/exception-base.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    ImgPage: typeof import('./src/components/Empty/ImgPage.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutMode: typeof import('./src/components/CustomHeaderActive/components/layout-mode.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    PageView: typeof import('./src/components/CustomHeaderActive/components/page-view.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectIcon: typeof import('./src/components/IconFont/select-icon.vue')['default']
    SettingMenu: typeof import('./src/components/CustomHeaderActive/components/setting-menu.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    TableColumnSetting: typeof import('./src/components/AdvancedTable/table-column-setting.vue')['default']
    TableEmpty: typeof import('./src/components/Empty/TableEmpty.vue')['default']
    ThemeColorSelect: typeof import('./src/components/CustomHeaderActive/components/themeColorSelect.vue')['default']
    ThemeMode: typeof import('./src/components/CustomHeaderActive/components/themeMode.vue')['default']
  }
}
