name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 根据需要指定 Node.js 版本

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: '8.7.1'  # 指定要安装的 pnpm 版本

      - name: Install dependencies
        run: pnpm install  # 使用 pnpm 安装依赖
        working-directory: ./

      - name: Build project
        run: pnpm run build --base=./  # 使用 pnpm 运行构建命令
        working-directory: ./

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.VUE3_NAIVE_TS_TOKEN }}
          publish_dir: ./dist
