name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: '8.7.1'
          dest: '~/setup-pnpm'
          run_install: 'false'
          package_json_file: 'package.json'
          standalone: 'false'

      - name: Check pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install
        working-directory: ./

      - name: Build project
        run: pnpm run build --base=./
        working-directory: ./

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          token: ${{ secrets.VUE3_NAIVE_TS_TOKEN }}
          branch: gh-pages
          folder: dist
